name: CI
run-name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        apt-get update -y -qq || true
        apt-get -qq install build-essential qtbase5-dev qt5-qmake cmake
    - name: compile+install librtdebug
      run: |
        git clone https://github.com/jens-maus/librtdebug.git librtdebug
        cd librtdebug
        [ -f Makefile ] && make distclean
        make PREFIX=/usr/local all install
    - name: compile+install libmedio
      run: |
        [ -f Makefile ] && make distclean
        make PREFIX=/usr/local all install
