name: CI
run-name: CI
on: [push]

env:
  CR_REGISTRY: fwpgit.fz-rossendorf.de
  CR_VERSION: b1ef9b1

jobs:
  build:
    name: Build [${{ matrix.target }}]
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - linux-x64-qt5
          - windows-shared-x64-posix-qt5
          #- windows-static-x64-posix-qt5

    steps:
      # checkout libmedio src
      - name: Checkout libmedio
        uses: actions/checkout@v4
        with:
          path: libmedio

      - name: Setup Environment
        run: |
          echo "BUILD_DATE=$(date -u +'%FT%T.%3NZ')" >> $GITEA_ENV
          echo "GIT_REF=$(git symbolic-ref -q --short HEAD || git describe --tags --exact-match)" >> $GITEA_ENV
          echo "GITEA_SHA7=$(echo ${GITHUB_SHA::7})" >> $GITEA_ENV

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CR_REGISTRY }}
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT_READ }}

      # get/install compiler suite
      - name: Setup cross-compiler docker environment
        run: |
          docker run --rm ${{ env.CR_REGISTRY }}/fwpm/${{ matrix.target }}:${{ env.CR_VERSION }} > ./dockcross
          chmod +x ./dockcross
          mkdir install

      # compile+install librtdebug
      - name: Compile+Install librtdebug
        run: |
          git clone --depth 1 https://github.com/jens-maus/librtdebug
          ./dockcross bash -c "cd librtdebug && cmake -Bbuild -S. -DPREFIX_PATH=\$(pwd)/../install && make -C build -j$(nproc) install"

      # compile+install libmedio
      - name: Compile+Install libmedio
        run: |
          ./dockcross bash -c "cd libmedio && cmake -Bbuild -S. -DPREFIX_PATH=\$(pwd)/../install && make -C build -j$(nproc) install"

      # upload install path as artifact
      - name: Upload artifact archive
        uses: christopherhx/gitea-upload-artifact@v4
        with:
          name: libmedio-${{ matrix.target }}-${{ env.GITEA_SHA7 }}
          path: install
