name: CI
run-name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: compile+install librtdebug
      run: |
        git clone https://github.com/jens-maus/librtdebug.git librtdebug
        cd librtdebug
        [ -f Makefile ] && make distclean
        make PREFIX=$(pwd)/build all install
    - name: make
      run: make
    - name: make test
      run: make test
