{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: pmedio
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - python
    - pip
    - pybind11
    - cmake
    - ninja
    - qt-main
    - libmedio

  host:
    - python
    - pip

  run:
    - python
    - numpy >=1.18

test:
  requires:
    - pytest
  imports:
    - pmedio
  source_files:
    - tests
  commands:
    - pytest tests

about:
  summary: 'python interface for libmedio'
  desription: |
    python interface to support libmedio supported medical imaging data
  license: APACHE
